# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 355)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.captchaImg = QtWidgets.QLabel(self.centralwidget)
        self.captchaImg.setGeometry(QtCore.QRect(120, 30, 371, 131))
        self.captchaImg.setText("")
        self.captchaImg.setObjectName("captchaImg")
        self.captchaEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.captchaEdit.setGeometry(QtCore.QRect(140, 210, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.captchaEdit.setFont(font)
        self.captchaEdit.setObjectName("captchaEdit")
        self.captchaButton = QtWidgets.QPushButton(self.centralwidget)
        self.captchaButton.setGeometry(QtCore.QRect(230, 270, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.captchaButton.setFont(font)
        self.captchaButton.setObjectName("captchaButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.captchaButton.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
