# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 625)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(270, 19, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("background: none;\n"
"color: white;")
        self.titleLabel.setText("")
        self.titleLabel.setObjectName("titleLabel")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-10, -10, 1071, 641))
        self.groupBox.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(65, 65, 65, 255), stop:1 rgba(0, 0, 0, 255));\n"
"border: none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.prevButton = QtWidgets.QPushButton(self.groupBox)
        self.prevButton.setGeometry(QtCore.QRect(175, 70, 31, 31))
        self.prevButton.setStyleSheet("background-color: transparent;\n"
"border-image: url(img/prev.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;")
        self.prevButton.setText("")
        self.prevButton.setObjectName("prevButton")
        self.durationLabel = QtWidgets.QLabel(self.groupBox)
        self.durationLabel.setGeometry(QtCore.QRect(790, 74, 61, 21))
        self.durationLabel.setStyleSheet("color: white;\n"
"background: none;")
        self.durationLabel.setObjectName("durationLabel")
        self.playButton = QtWidgets.QPushButton(self.groupBox)
        self.playButton.setGeometry(QtCore.QRect(85, 50, 71, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.playButton.setFont(font)
        self.playButton.setStyleSheet("background-color: transparent;\n"
"border-image: url(img/play.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;")
        self.playButton.setText("")
        self.playButton.setObjectName("playButton")
        self.nextButton = QtWidgets.QPushButton(self.groupBox)
        self.nextButton.setGeometry(QtCore.QRect(225, 70, 31, 31))
        self.nextButton.setStyleSheet("background-color: transparent;\n"
"border-image: url(img/next.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;")
        self.nextButton.setText("")
        self.nextButton.setObjectName("nextButton")
        self.volumeSlider = QtWidgets.QSlider(self.groupBox)
        self.volumeSlider.setGeometry(QtCore.QRect(899, 74, 131, 22))
        self.volumeSlider.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.5, stop:0 rgba(98, 9, 54, 255), stop:1 rgba(33, 13, 68, 255))\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: rgb(118, 118, 118);\n"
"\n"
"\n"
";\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: rgb(216, 216, 216);\n"
"    width: 14px;\n"
"    margin: -5px;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: rgb(240, 240, 240);\n"
"\n"
"}")
        self.volumeSlider.setMinimum(0)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setSingleStep(2)
        self.volumeSlider.setPageStep(10)
        self.volumeSlider.setProperty("value", 50)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.volumeSlider.setObjectName("volumeSlider")
        self.musicSlider = QtWidgets.QSlider(self.groupBox)
        self.musicSlider.setGeometry(QtCore.QRect(280, 70, 501, 31))
        self.musicSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.musicSlider.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494, x2:1, y2:0.5, stop:0 rgba(98, 9, 54, 255), stop:1 rgba(33, 13, 68, 255))\n"
"\n"
"}\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: rgb(118, 118, 118);\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    width: 14px;\n"
"    margin: -5px;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: rgb(240, 240, 240);\n"
"\n"
"}")
        self.musicSlider.setMinimum(0)
        self.musicSlider.setOrientation(QtCore.Qt.Horizontal)
        self.musicSlider.setObjectName("musicSlider")
        self.artistLabel = QtWidgets.QLabel(self.groupBox)
        self.artistLabel.setGeometry(QtCore.QRect(280, 50, 491, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.artistLabel.setFont(font)
        self.artistLabel.setStyleSheet("background: none;\n"
"color: white;")
        self.artistLabel.setText("")
        self.artistLabel.setObjectName("artistLabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 1051, 140))
        self.groupBox_2.setStyleSheet("border: none; background: rgb(24, 24 ,24);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.shuffleButton = QtWidgets.QPushButton(self.groupBox_2)
        self.shuffleButton.setGeometry(QtCore.QRect(10, 40, 30, 20))
        self.shuffleButton.setStyleSheet("background-color: transparent;\n"
"border-image: url(img/shuffle.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;")
        self.shuffleButton.setText("")
        self.shuffleButton.setObjectName("shuffleButton")
        self.repeatThis = QtWidgets.QPushButton(self.groupBox_2)
        self.repeatThis.setGeometry(QtCore.QRect(10, 90, 30, 20))
        self.repeatThis.setStyleSheet("background-color: transparent;\n"
"border-image: url(img/repeatthis.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;")
        self.repeatThis.setText("")
        self.repeatThis.setObjectName("repeatThis")
        self.volumeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.volumeButton.setGeometry(QtCore.QRect(860, 66, 20, 18))
        self.volumeButton.setStyleSheet("background-color: transparent;\n"
"border-image: url(img/medium.png);\n"
"background: none;\n"
"border: none;\n"
"background-repeat: none;")
        self.volumeButton.setText("")
        self.volumeButton.setObjectName("volumeButton")
        self.imgLabel = QtWidgets.QLabel(self.groupBox)
        self.imgLabel.setGeometry(QtCore.QRect(60, 190, 150, 150))
        self.imgLabel.setStyleSheet("background: transparent;\n"
"")
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.refreshButton = QtWidgets.QPushButton(self.groupBox)
        self.refreshButton.setGeometry(QtCore.QRect(20, 595, 74, 31))
        self.refreshButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #ff3333;\n"
"    color: #fff;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #5c5c5c;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #ff4747;\n"
"\n"
"}\n"
"")
        self.refreshButton.setObjectName("refreshButton")

#-----------------------

        self.offlineButton = QtWidgets.QPushButton(self.groupBox)
        self.offlineButton.setGeometry(QtCore.QRect(112, 370, 43, 31))
        self.offlineButton.setStyleSheet("background-color: transparent;\n"
                                         "border-image: url(img/offline_off.png);\n"
                                         "background: none;\n"
                                         "border: none;\n"
                                         "background-repeat: none;")
        self.offlineButton.setText("")
        self.offlineButton.setObjectName("offlineButton")

        self.aboutButton = QtWidgets.QPushButton(self.groupBox_2)
        self.aboutButton.setGeometry(QtCore.QRect(1025, 6, 20, 20))
        self.aboutButton.setStyleSheet("background-color: transparent;\n"
                                         "border-image: url(img/about.png);\n"
                                         "background: none;\n"
                                         "border: none;\n"
                                         "background-repeat: none;")
        self.aboutButton.setText("")
        self.aboutButton.setObjectName("aboutButton")
#-----------------------
        self.groupBox_2.raise_()
        self.prevButton.raise_()
        self.durationLabel.raise_()
        self.playButton.raise_()
        self.nextButton.raise_()
        self.volumeSlider.raise_()
        self.musicSlider.raise_()
        self.artistLabel.raise_()
        self.imgLabel.raise_()
        self.refreshButton.raise_()
        self.offlineButton.raise_()
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(250, 140, 801, 485))
        self.listWidget.setStyleSheet("QListView\n"
"{\n"
"  background-color: transparent;\n"
"  alternate-background-color: transparent;\n"
"   border : none;\n"
"   color: #fff;\n"
"   font-size: 15px;\n"
"   show-decoration-selected: 1;\n"
"   outline: 0;\n"
"   border: 0px solid #1d1d1d;\n"
"}\n"
"QListView::disabled\n"
"{\n"
"   background-color: transpent;\n"
"   color: #1b1b1b;\n"
"    border: none;\n"
"}\n"
"QListView::item\n"
"{\n"                       
"    background-color: transparent;\n"
"    padding: 5px;\n"
"}\n"
"QListView::item:selected:!active\n"
"{\n"
"  color: #1DB954;\n"
"}\n"
"QListView::item:selected\n"
"{\n"
"  color: #1DB954;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: transparent;\n"
"   border: none;\n"
"   color: #1DB954;\n"
"\n"
"}")
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setObjectName("listWidget")
        self.groupBox.raise_()
        self.titleLabel.raise_()
        self.listWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.durationLabel.setText(_translate("MainWindow", "0.00 / 0.00"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
